### ISSUE TITLE
Active forks?

### ISSUE THREAD

**Issue by sphh** [eriknystrom/ObjectListView2#12]
Is there an actively maintained fork of this fabulous module?

I found [ObjectListView3](https://github.com/driscollis/ObjectListView3) by @driscollis, but there is no way to open an issue or create a pull request (@driscollis?) …

**Comment by driscollis** [comment]
Looks like I must have messed up configuring the repo. I just added issues, I think. 

ObjectListView3 is supposed to allow for PRs too, so I'm not sure what I have messed up there

**Comment by eriknystrom** [comment]
@sphh @driscollis 

Apologies for the inactivity. Been hard to find time to do anything and haven't used this module in forever. I am glad there is a new fork of this :) I will update the readme to point to olv3 repo and mark as not maintained currently. I hope to get back into this kind of work in the future.

**Comment by driscollis** [comment]
@eriknystrom I am happy to have you help with OLV3 too in the future too as I don't have a lot of experience in open source land.

**Comment by sphh** [comment]
Thanks to both of you!

@driscollis: The PRs were only open for member of the teams and not for everyone.

I guess I can close this issue now.

**Comment by driscollis** [comment]
Looks like enabling Issues on my fork has also enabled PRs or something.
